### ISSUE TITLE
Inkrementální harvestace

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/nkod#1]
V případě že má poskytovatel dat větší množství datových sad by měl NKOD poskytnout mechanizmus pro harvestování pouze změněných metadatových záznamů.

To by vyžadovalo:
- Definici mechanizmu komunikace hranice, od které má harvestace probíhat
- Implementaci mechanizmu na straně poskytovatele dat (LKOD)
- Implementaci mechanizmu na straně NKOD

K diskuzi:
- Je takové řešení opravdu potřeba?
- Jaký přesně problém na straně poskytovatele vzniká?
- Je to počet HTTP požadavků? Existuje měření, které by ukazovalo že je to pro webserver skutečný problém?

Výhodou stávajícího řešení je bezestavovost, a tedy jednoduchost NKOD.

Možnosti řešení:
- Poskytování DCAT-AP dat LKOD přes SPARQL endpoint

**Comment by MichalMed** [comment]
Ještě je u inkrementace potřeba vyřešit problém s mazáním záznamů.
Je potřeba vyřešit na straně LKOD i NKOD.

**Comment by jakubklimek** [comment]
Po opakovaných analýzách se inkrementální harvestace stále jeví jako nepotřebná, vzhledem ke zesložítění celého procesu jak na straně NKOD, tak LKODů. V budoucnu lze znovu otevřít.
