### ISSUE TITLE
Umožnit katalogizovat služby pro přístup k datům

### ISSUE THREAD

**Issue by ezr-ondrej** [opendata-mvcr/nkod#10]
Umožnit distribuci typu OpenAPI

**Comment by jakubklimek** [comment]
Předpokládám, že je míněna webová služba založená na HTTP, popsaná pomocí [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md).
V právě probíhající revizi standardu DCAT se [katalogizace webových služeb](https://github.com/w3c/dxwg/issues/56) řeší. Bude obsahovat odkaz na endpoint služby a odkaz na popis služby.

**Comment by jakubklimek** [comment]
Podpora pro katalogizaci datových služeb byla přidána do nové verze [OFN Rozhraní katalogů otevřených dat](https://ofn.gov.cz/rozhraní-katalogů-otevřených-dat/2021-01-11/). Příští verze NKOD je tedy bude umět harvestovat.
