### ISSUE TITLE
Překliknutí do anglické verze nefunguje v prohlížeči Firefox a IE11

### ISSUE THREAD

**Issue by michalkuban** [opendata-mvcr/nkod#11]
Po kliknutí na anglickou vlaječku vpravo nahoře na [data.gov.cz](https://data.gov.cz/) nefunguje přepnutí do anglické verze. Nefunguje to ve Mozile Firefox ESR 52.9.0  ani v IE 11 verze 11.0.9600.18893. 

Funguje to ale v Google Chrome Verze 67.0.3396.99

**Comment by jakubklimek** [comment]
Tato issue patří do https://github.com/opendata-mvcr/opendata-mvcr.github.io a https://github.com/linkedpipes/dcat-ap-viewer, zřejmě se týká o problém s Bootstrapem.

IE11 podporován není (kdo trvá na MS prohlížeči, může použít Edge).

Firefox řeší @skodapetr..

**Comment by michalkuban** [comment]
Aha, já přidal špatně do sekce NKOD jaok nástroje a ne do stránky. OK. Sorry. Mám ho smazat a přesunout?

**Comment by jakubklimek** [comment]
Dobrý, to zvládneme ;)

**Comment by jakubklimek** [comment]
Na data.gov.cz fixnuto https://github.com/opendata-mvcr/opendata-mvcr.github.io/commit/55c15daf5fec847dfbda809209f8346cf163b3f7
