### ISSUE TITLE
Umožnit využití SW pro NKOD i pro LKOD

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/nkod#12]
Pokud by se SW pro NKOD doplnil o uživatelské účty, mohl by se využít i jako LKOD, což by využila řada OVM.

**Comment by ezr-ondrej** [comment]
Souhlasím, dokonce bychom to v rámci našeho LKOD možná i mohli udělat a poskytnout.
Kde je repositář s kódem NKOD?

**Comment by jakubklimek** [comment]
Část formulářů se vyvíjí zde: https://github.com/linkedpipes/dcat-ap-forms-vue
Část zobrazovací se vyvíjí zde: https://github.com/linkedpipes/dcat-ap-viewer - aktuálně v branch nkod
Pro transformaci dat je používáno https://github.com/linkedpipes/etl - konkrétní pipeline budou publikovány až budou hotové.

**Comment by jakubklimek** [comment]
Aktuálně pomocí nástrojů pro NKOD běží [LKOD MVČR](https://github.com/opendata-mvcr/lkod-mvcr)

**Comment by jakubklimek** [comment]
Jak zprovoznit LKOD pomocí nástrojů NKOD je popsáno v tomto repo: https://github.com/opendata-mvcr/lkod
