### ISSUE TITLE
Nefunkčnost filtrování datových sad podle nových přírůstků 

### ISSUE THREAD

**Issue by michalkuban** [opendata-mvcr/nkod#16]
Při filtrování datové sady skrze kalendář Od-Do u poskytovale datové sadě nevidím nově zkataligozvané datové sady. Ačkoliv vím, že datové sady byla před několika dny přidány. 
![MVčr](https://user-images.githubusercontent.com/8858125/56802462-6688e300-6820-11e9-96ab-47687f69f50a.JPG)

**Comment by jakubklimek** [comment]
Kalendář je popsán jako časové pokrytí od - do. To jsou metadata datové sady. Pokud je datová sada nemá (poskytovatel je nevyplnil), nelze ji podle toho najít.

Popsaný postup by vyžadoval hledání dle data přidání datové sady do katalogu, což v NKOD není - není to ani v LKODech.
