### ISSUE TITLE
Zahrnout do NKOD/LKOD MF data Státní pokladny

### ISSUE THREAD

**Issue by petrbouchal** [opendata-mvcr/nkod#21]
Tato data (https://monitor.statnipokladna.cz/) momentálně nejsou nijak katalogizována a jediný způsob, jak získat jejich metadata, je z nezdokumentovaného API webového front endu. Výsledek je, že URLs datových exportů se mohou bez varování změnit (což se právě stalo) a není způsob, jak takové změny detekovat. V takovém případě se všechny systémy závislé na těchto datech bez varování rozbijí (což se právě stalo).

**Comment by jakubklimek** [comment]
MF ČR to [vyčítáme pravidelně](https://opendata.gov.cz/statistika:plnění-nařízení-vlády-2019-11-27#monitor_státní_pokladna).

**Comment by petrbouchal** [comment]
Děkuju, tušil jsem, že problém nebude ve vašem nezájmu. Proto mi přišlo užitečné vám tady zalogovat konkrétní následek, abyste s tím mohli operovat.

S podporou SP si píšu častěji než bych sám chtěl, takže to ode mě už mají.
