### ISSUE TITLE
Neúplné katalogizační záznamy

### ISSUE THREAD

**Issue by SmallhillCZ** [opendata-mvcr/nkod#22]
Na MF dle směrnice katalogizujeme i takové datové sady, kde bylo rozhodnuto o jejich nepublikaci. K takové datové sadě je vytvořen katalgizační záznam a připojeny důvody, proč nebyla publikována.

Tyto sady bychom také rádi publikovali v rámci NKOD.

**Comment by jakubklimek** [comment]
V následující verzi NKOD bude možné publikovat datovou sadu bez distribucí, což je technicky ono.

Zbývají 2 otázky:
- Patří toto do NKOD?
- Stačí, že taková datová sada bude jako každá jiná, jen popis bude obsahovat důvody, proč není publikovaná, nebo je třeba takovou datovou sadu explicitně označit jako nepublikovanou?

**Comment by jakubklimek** [comment]
Datové sady, které nejsou otevřené, zatím patří pouze do interního katalogu organizace. Do NKOD se mohou dostat až tehdy, když se z něj stane katalog všech dat (řízený přístup, neotevřená, ...) a ne pouze těch otevřených.
