### ISSUE TITLE
Uvést informace ve formuláři pro registraci datové sady a lokálního katalogu otevřených dat, že proces registrace trvá 24 hodin 

### ISSUE THREAD

**Issue by michalkuban** [opendata-mvcr/nkod#23]
Registrační formuláře pro [registraci datové sady ](https://data.gov.cz/formul%C3%A1%C5%99/registrace-datov%C3%A9-sady) a [registraci nového lokálního katalogu otevřených dat](https://data.gov.cz/formul%C3%A1%C5%99/registrace-lok%C3%A1ln%C3%ADho-katalogu) neobsahuje informaci, že proces registrace po odeslání vygenerovaného souboru datovou zprávou trvá 24 hodin. Často se tak registrující subjekt kontaktuje správce v NKODu a zjišťuje, zda registrace byla úspěšná.  S touto informací si registrující subjekt může lépe plánovat mediální kampaň a odstranit nejasnosti při spuštění.

**Comment by jakubklimek** [comment]
24 hodin je zavádějící informace. Když někdo registraci zašle večer, poté, co už byly záznamy pro noční běh zpracovány, objeví se až  třetí den. Naopak když to stihne před zpracováním, obeví se už za 10 hodin.

Navrhuji přidat sdělení: "Přijaté záznamy jsou zpracovávány dávkově, typicky přes noc."

**Comment by michalkuban** [comment]
Souhlas.

**Comment by jakubklimek** [comment]
https://github.com/linkedpipes/dcat-ap-forms/commit/524a4506cec4dfb07f58319b1b90834760435d0d
