### ISSUE TITLE
Informovat o změně namespace OVM

### ISSUE THREAD

**Issue by petrbouchal** [opendata-mvcr/nkod#24]
Všiml jsem si, že v NKOD se změnil namespace OVM - což tuším udělá nepříjemnosti všem, kdo si vytahují seznam datasetů za konkrétní poskytovatele.

Tuším, že se změnily i jiné věci, ale tuto jsem identifikoval jako příčinu rozbití kódu...

Starý: https://data.gov.cz/zdroj/ovm/
Nový: https://rpp-opendata.egon.gov.cz/odrpp/zdroj/orgán-veřejné-moci/

Stálo by za to o tom někde informovat, aby uživatelé dokázali rozklíčovat chybu?

Zároveň by pak bylo fajn upravit kód v [tutoriálu](https://data.gov.cz/%C4%8Dl%C3%A1nky/znalostn%C3%AD-grafy-03-sparql).

**Comment by jakubklimek** [comment]
Ano, poskytovatele, kteří jsou OVM, jsme s aktualizací nalinkovali "napřímo" na RPP, místo původního "proxy" IRI.
Jsme si vědomi, že nám chybí kanál směrem k uživatelům NKOD, které bychom takto mohli informovat, budeme to řešit. Máme testovací instanci (https://pod-test.mvcr.gov.cz/datové-sady) pro nové verze, kde tato změna už nějakou dobu byla, ale je jasné, že ne každý o tom ví.
Články (tutoriály) upravíme.

**Comment by martinnec** [comment]
Dobrý den Petře, články jsme opravili. Bylo nutno opravit všechny 3 zatím vydané články ke znalostním grafům. Dopad změn v datech NKOD na články byl trochu větší než jen změna IRI, čili i ty články se změnily trochu více. Nicméně, ve 3. díle nakonec dotazy vrací to samé, jako před tím. Díky za issue.

**Comment by petrbouchal** [comment]
Díky - je fajn mít to pro studijní účely aktualizované, identifikovat zrovna tuhle chybu není nic moc, když se člověk snaží pochopit celou věc.

Nechám na vás, jestli chcete issue zavřít nebo držet do případného update pro uživatele.
