### ISSUE TITLE
Nefunkční filtrování klíčových slov u datových sad

### ISSUE THREAD

**Issue by michalkuban** [opendata-mvcr/nkod#25]
Po kliknutí na kličové slovo u datasetu například "[Rastrový podklad](https://data.gov.cz/datov%C3%A9-sady?keyword=%C3%9Azemn%C3%AD%20pl%C3%A1n%20Plze%C5%88)", tak se dostanu na výčet [všech datových sad v NKOD](https://data.gov.cz/datov%C3%A9-sady?keyword=Rastrov%C3%BD%20podklad) bez to, aniž by byly vyfiltrovány datové sady oštítkované jako Rastrový podklad. Správně to má vést https://data.gov.cz/datové-sady?klíčová-slova=Rastrový%20podklad

**Comment by jakubklimek** [comment]
Opraveno v https://github.com/linkedpipes/dcat-ap-viewer/commit/0a192c3e8b20145f229a474848786a9425efac71
