### ISSUE TITLE
Různé odpovědi na stejný dotaz

### ISSUE THREAD

**Issue by petrbouchal** [opendata-mvcr/nkod#27]
Zaznamenal jsem dva dny po sobě podivnou situaci, kdy SPARQL endpoint vrací v odpovědi na jednoduchý dotaz "všechny sady od ČSÚ" (níže) v rozpětí minut různé počty řádek - napřed 15, pak 5, pak 4, pak 1 a po čase zase všech 723. Přihodilo se to včera i dnes (s jinými počty vrácených řádků). 

Pochopitelně nedokážu popsat, jak to zreplikovat, ale raději reportuji. Doslova jsem jen pouštěl ten stejný dotaz dokola v rozhraní na data.gov.cz/sparql; přes HTTP request z mé aplikace se to chovalo stejně (tj. stejné dotazy dvěma jinými cestami ve stejný čas generovaly stejné chybné odpovědi).  

Pokud něco dělám špatně, budu rád za upozornění. Zkoušel jsem i jiné kódy poskytovatelů a tam se to zdálo v pořádku, ale netestoval jsem to tak důkladně.

Dotaz:

```
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ovmr: <https://rpp-opendata.egon.gov.cz/odrpp/zdroj/orgán-veřejné-moci/>

 SELECT ?dataset_iri
 WHERE {
   GRAPH ?g {
     ?dataset_iri dcterms:publisher ovmr:00025593
   }
} LIMIT 1000
```

**Comment by jakubklimek** [comment]
To se může stát, pokud to zkoušíte v době updatu endpointu. Ten aktuálně trvá celkem cca 40 minut a probíhá denně kolem 20:30. Jednotlivé datové sady jsou nejprve vymazány, a pak je nahrán nový obsah, což trvá. Šlo by to dělat i jinak (např. tvořit jinou databázi a pak přepnout), ale zatím to nebylo třeba.

**Comment by petrbouchal** [comment]
Děkuji za vysvětlení, tak to jsem se jen trefil s časováním.
