### ISSUE TITLE
Tlačítko "Zobrazit další" u seznamu datových sad nefunguje

### ISSUE THREAD

**Issue by michalkuban** [opendata-mvcr/nkod#29]
Na seznamu datových sad podle poskytovatele se při kliknutí na tlačítko "Zobrazit další" nenačtou další datové sady. Tedy ze strany 1 na stranu 2. Tlačítko se proklikne ale stránka se neposune na číslo dva. 

https://data.gov.cz/datov%C3%A9-sady?poskytovatel=https%3A%2F%2Frpp-opendata.egon.gov.cz%2Fodrpp

https://user-images.githubusercontent.com/8858125/135241229-9fecd67d-a4cb-4203-b05e-1cab7d72ce4a.mov

%2Fzdroj%2Forg%C3%A1n-ve%C5%99ejn%C3%A9-moci%2F00006947

**Comment by jakubklimek** [comment]
Ono se to na stránku 2 ani prokliknout nemá, protože se donačtou záznamy do aktuální stránky. Ale mělo by to zůstat donačtené.
