### ISSUE TITLE
Při sklízení CKANu odhadnout MIME z pole format, pokud je pole mime null

### ISSUE THREAD

**Issue by mordae** [opendata-mvcr/nkod#5]
V kódu CKANu lze nalézt mapování pole `format` na MIME type[^1]. V případě, že má pole `mimetype` u zdroje hodnotu `null`, mohlo by se při sklizni vyvodit z pole `format` dle tohoto mapování.

[^1]: https://github.com/ckan/ckan/blob/master/ckan/config/resource_formats.json

**Comment by jakubklimek** [comment]
Obecně problém s CKAN je, že příliš nepodporuje Internetové standardy. [Uvedené mapování](https://github.com/ckan/ckan/blob/master/ckan/config/resource_formats.json) mapuje CKAN formáty na řadu neexistujících (application/x-*) a nebo léta zastaralých (application/x-n3) MIME typů. To znamená, že je pro automatické zpracování nepoužitelné.

To vede na to, že by bylo třeba extra pro CKAN mapovat formáty ručně na základě výskytů v harvestovaných datech, což je nesystémové řešení. Nejčastěji používaných [MIME-Typů](https://www.iana.org/assignments/media-types/media-types.xhtml) ale není příliš a lze je uživatelům CKAN nabízet k vyplnění jako číselník. Vzhledem k nutnosti [upravovat CKAN pro NKOD](https://opendata.gov.cz/nastroj:zprovozneni-lokalniho-katalogu-na-bazi-ckan) tak jako tak je systémovější řešení vyplňovat tuto položku správně. Že to jde je vidět třeba na CKANu https://linked.opendata.cz.

**Comment by mordae** [comment]
A máme někde patche, které by navedly CKAN správně vyplnit pole `mime`?

**Comment by jakubklimek** [comment]
Nemáme. Do zmíněné instance je to zapsáno pomocí API, nikoliv skrz CKAN formulář.

**Comment by jakubklimek** [comment]
V nové verzi [OFN Rozhraní katalogů otevřených dat](https://ofn.gov.cz/rozhraní-katalogů-otevřených-dat/2021-01-11/) již rozhraní CKAN API není podporováno kvůli rostoucímu nesouladu s webovým standardem DCAT. Podpora pro harvestaci skrze CKAN API v NKOD tedy již nebude rozvíjena.
