### ISSUE TITLE
Periodicita aktualizace u jednorázově zadaných či nepravidelně aktualizovaných dat

### ISSUE THREAD

**Issue by janaslo** [opendata-mvcr/nkod#7]
Povinným atributem datové sady je periodicita aktualizace dle normy [ISO 8601](https://project-open-data.cio.gov/iso8601_guidance/#accrualperiodicity). 

Jaká je prosím správná hodnota pro datové sady, jejichž distribuce jsou vloženy jen jednorázově, případně jsou aktualizovány nepravidelně/občasně?

**Comment by jakubklimek** [comment]
ISO norma tyto hodnoty neumožňuje. Nicméně částečně je tento požadavek řešen. V NKOD již nyní dochází k převodu hodnot dle ISO na hodnoty [evropského číselníku frekvencí](https://publications.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/frequency), který je povinný pro DCAT-AP v1.1. Analýzou již existujících hodnot v datech byl definován následující převodník:

iso | frequency
-- | --
R/P2Y | BIENNIAL
R/P1Y | ANNUAL
R/P6M | ANNUAL_2
R/P3M | QUARTERLY
R/P1M | MONTHLY
R/P1W | WEEKLY
R/P1D | DAILY
R/PT1S | UPDATE_CONT
R/P4Y | OTHER
R/P10Y | OTHER
R/P50Y | OTHER
dle-potřeby | IRREG
jednorázově | NEVER
nikdy | NEVER

Jak je vidět, převod zahrnuje i řetězce dle ISO nevalidní, vzniklé lidovou tvořivostí.

Doporučení tedy je: Pro CKAN API (stávající JSON rozhraní lokálních katalogů) používejte hodnoty ze sloupce `iso`, v DCAT-AP reprezentaci pak budou odkazovat na odpovídající hodnotu evropského číselníku. V budoucí DCAT-AP reprezentaci LKOD samozřejmě použijte URI z evropského číselníku.

**Comment by janaslo** [comment]
Díky! Bylo by užitečné mít takové převodníky snadno dohledatelné, klidně s poznámkou, že je silně preferovaná některá validní varianta. Jinak to vede k tomu, že je u některých datasetů vybrána validní hodnota, která ovšem není pravdivá, anebo právě k bujení lidové tvořivosti.

**Comment by jakubklimek** [comment]
Přidal jsem ty dvě speciální hodnoty do [návodu na přípravu katalogizačního záznamu](https://opendata.gov.cz/cinnost:priprava-katalogizacniho-zaznamu#atributy_datové_sady). Tam se také odkazuje [popis funkce package_show](https://opendata.gov.cz/nastroj:ckan-api#package_show).

**Comment by janaslo** [comment]
Perfektní, díky.
