### ISSUE TITLE
Varianty podmínek užití

### ISSUE THREAD

**Issue by janaslo** [opendata-mvcr/nkod#8]
Na workshopu byla prezentována potřeba specifikovat podmínky užití ve čtyřech kategoriích, přičemž v každé jsou na výběr jen dvě možnosti: 

- distribuce neobsahuje data chráněná v této kategorii
- distribuce je chráněná a uvolněná pod konkrétní licencí, která je určená kategorií - např. pro autorská práva je to CC-BY

Jak se bude postupovat u distribucí, které budou chráněné a uvolněné za jiných podmínek, než je licence uvedená ve druhém bodu? Např. jiná varianta CC, nebo úplně jiná (volná) licence.

**Comment by jakubklimek** [comment]
Řešení tohoto dotazu by mělo být synchronizováno s [Návodem na stanovení podmínek užití](https://opendata.gov.cz/cinnost:stanoveni-podminek-uziti).

**Comment by jkb-misek** [comment]
@janaslo Stránka [Návod na stanovení podmínek užití](https://opendata.gov.cz/cinnost:stanoveni-podminek-uziti) už byla aktualizována, takže odpovídá současné dobré praxi.
Obecně - pokud chcete použít vlastní licenci, samozřejmě to udělat můžete tím, že do metadatového záznamu distribuce vložíte na patřičné místo odkaz na Vámi zvolenou licenci. Tato možnost je zachována, byť není doporučena. Pokud to bude Váš vlastní text bude tam problém se strojovou čitelností, která je v případě CC zajištěna. 
Mohu se zeptat na konkrétní situaci, proč chcete použít jiné licence?
Pokud byste měla další dostazy, klidně prosím pište.

**Comment by janaslo** [comment]
Narazili jsme na to například u brněnského městského katalogu, kde jsou k dispozici data chráněná (alespoň prozatím) jinými typy licencí. Byla by škoda je jen kvůli tomu neposkytnout veřejnosti prostřednictvím lokálního katalogu.

Chápu a nerozporuji výhody doporučeného postupu; přišla by mi OK i striktní varianta, že do NKOD převezmete pouze datové sady s danou licencí (pokud je nějaká potřeba). Jen bych se asi nerada dočkala nějakých seznamů hříšníků používajících nesprávné licence v situaci, kdy je snaha data zveřejnit, byť ne ideálním způsobem.

**Comment by jkb-misek** [comment]
@janaslo Mohla byste mě prosím odkázat na ta data chráněná jinak? Teď jsem trochu náhodně procházel ten městský katalog a narazil jsem většinou na CC BY (pravda odkazovanou naprosto nesmyslně na "https://opendefinition.org/licenses/cc-by/"). A pak jsem tam našel případy jako je tento: https://data.brno.cz/dataset/?id=dokoncene-byty-dle-mestskych-casti, kdy rozhodně nemůže být použita žádná licence, protože tam prostě není žádný obsah chráněný právem duševního vlastnictví.
Není myslím cílem vytvářet "seznamy hříšníků", ale spíš postupně vzdělávat a ukazovat, jak to dělat správně.
Nicméně, obecně, poskytovatel dat samozřejmě může zvolit vlastní licenci, NKOD mu to umožní.

**Comment by jakubklimek** [comment]
@janaslo Pokud by stále nebylo něco jasné, ozvěte se prosím.
